# Generated by Django 6.0.3 on 2026-03-18 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('facilities', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('aadhar_no', models.CharField(max_length=12, unique=True)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('addr_l1', models.TextField()),
                ('addr_l2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=6)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'citizen',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lab_test',
            },
        ),
        migrations.CreateModel(
            name='MedicalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_invasive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'medical_procedure',
            },
        ),
        migrations.CreateModel(
            name='CitizenContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clinical.citizen')),
            ],
            options={
                'db_table': 'citizen_contact',
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders_received', to='facilities.healthfacility')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.labtest')),
            ],
            options={
                'db_table': 'lab_order',
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_data', to='clinical.laborder')),
            ],
            options={
                'db_table': 'lab_result',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField()),
                ('dose_no', models.IntegerField()),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.healthfacility')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='clinical.citizen')),
                ('vaccine', models.ForeignKey(limit_choices_to={'type': 'vaccine'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
            options={
                'db_table': 'vaccination',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_visits', to='facilities.healthfacility')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinical.citizen')),
            ],
            options={
                'db_table': 'visit',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transfer', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.citizen')),
                ('from_fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='facilities.healthfacility')),
                ('to_fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='facilities.healthfacility')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='clinical.visit')),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
        migrations.CreateModel(
            name='ProcedureTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.medicalprocedure')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='clinical.visit')),
            ],
            options={
                'db_table': 'procedure_taken',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('medicine', 'Medicine'), ('vaccine', 'Vaccine')], max_length=10)),
                ('dosage', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinical.visit')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='clinical.visit'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.disease')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinical.visit')),
            ],
            options={
                'db_table': 'diagnosis',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='facilities.ward')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='clinical.citizen')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.visit')),
            ],
            options={
                'db_table': 'admission',
            },
        ),
        migrations.CreateModel(
            name='LabTestProvided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.healthfacility')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.labtest')),
            ],
            options={
                'db_table': 'lab_test_provided',
                'unique_together': {('test', 'fac')},
            },
        ),
        migrations.CreateModel(
            name='ProcedureProvided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.healthfacility')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.medicalprocedure')),
            ],
            options={
                'db_table': 'procedure_provided',
                'unique_together': {('procedure', 'fac')},
            },
        ),
        migrations.CreateModel(
            name='DoctorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.healthcareworker')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.visit')),
            ],
            options={
                'db_table': 'doctor_visit',
                'unique_together': {('visit', 'doctor')},
            },
        ),
    ]
