ALTER TABLE works ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE doctor_visit ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE lab_test_provided ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE lab_test_provided ADD COLUMN id SERIAL PRIMARY KEY;
