# Generated by Django 6.0.3 on 2026-03-18 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_l1', models.TextField()),
                ('addr_l2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=6)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facilities.place')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Pharmacy', 'Pharmacy'), ('Laboratory', 'Laboratory')], max_length=30)),
            ],
            options={
                'db_table': 'health_facility',
            },
            bases=('facilities.place',),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facilities.place')),
            ],
            options={
                'db_table': 'warehouse',
            },
            bases=('facilities.place',),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='General', max_length=30)),
                ('occupied', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=10)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='facilities.healthfacility')),
            ],
            options={
                'db_table': 'wards',
            },
        ),
        migrations.CreateModel(
            name='HealthFacContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('healthfac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='facilities.healthfacility')),
            ],
            options={
                'db_table': 'healthfac_contact',
            },
        ),
        migrations.CreateModel(
            name='WarehouseContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='facilities.warehouse')),
            ],
            options={
                'db_table': 'warehouse_contact',
            },
        ),
    ]
